language: node_js
cache:
  yarn: true
  directories:
    - ~/.cache
node_js:
  - node
install:
  - npx lerna bootstrap
script:
  - yarn build
  - yarn test

notifications:
  email:
    on_success: never
    on_failure: never
